### ISSUE TITLE
Is x-ua-compatible necessary?

### ISSUE THREAD

**Issue by jaywilliams** [sesh/base.html#4]
IE 11 has a 1% global market share, is the meta tag needed for a short base HTML template in 2021?

https://github.com/sesh/base.html/blob/7245bc776ea51c34cb0e75042fd62ac5f090225e/index.html#L6

Update: Apparently that meta tag only applies to IE9-10, so we're looking at 0.3% global usage. 

> Starting with IE11, edge mode is the preferred document mode; it represents the highest support for modern standards available to the browser.
> [Source](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/dev-guides/bg182625(v=vs.85)?redirectedfrom=MSDN#document-mode-changes)

**Comment by sesh** [comment]
@jaywilliams forgot to say thanks for this bug report when I closed it earlier this week! And thanks for checking out the template, glad a few people from lobste.rs came to look at the source :)

**Comment by jaywilliams** [comment]
No problem, glad to help improve something, albeit a tiny tweak.
